aspect-build/bazel-examples

angular-ngc/packages/lib-a/src/lib/lib-b.component.spec.ts
angular-ngc/tools/ngc.esbuild.ts

fix: enable ngc JIT mode for angular-ngc unit tests

---

angular-ngc/WORKSPACE.bazel
angular/WORKSPACE.bazel
bzlmod/MODULE.bazel
directory_path/WORKSPACE
jest/WORKSPACE
nestjs/WORKSPACE
next.js/WORKSPACE.bazel
pnpm-workspaces/WORKSPACE.bazel
protobufjs/WORKSPACE.bazel
react-cra/WORKSPACE
rules_nodejs_to_rules_js_migration/WORKSPACE
ts_project_transpiler/WORKSPACE
vue/WORKSPACE.bazel
write_source_files/WORKSPACE

Also latest rules_swc and bazel-lib

chore: update to rules_js v1.14.0

---

bzlmod/MODULE.bazel
bzlmod/README.md
bzlmod/src/BUILD.bazel

This reverts commit 33f8032419008772431a9e1398d999f908449f76.

chore: show swc used with bzlmod

---

angular-ngc/defs.bzl
angular-ngc/packages/lib-a/src/lib/lib-b.component.spec.ts

Thanks @jackvincentnz for pointing this out and helping with the fix.

example(angular-ngc): fix and add test for test components containing tested components

---

angular-ngc/WORKSPACE.bazel
angular/WORKSPACE.bazel
bazelrc/.aspect/bazelrc/ci.bazelrc
bazelrc/WORKSPACE
bzlmod/MODULE.bazel
check-npm-determinism/WORKSPACE
directory_path/WORKSPACE
eager-fetch/WORKSPACE
git_push/MODULE.bazel
go_workspaces/WORKSPACE
jest/WORKSPACE
nestjs/WORKSPACE
next.js/WORKSPACE.bazel
oci_go_image/MODULE.bazel
oci_java_image/MODULE.bazel
pnpm-workspaces/WORKSPACE.bazel
prisma/WORKSPACE
protobufjs/WORKSPACE.bazel
react-cra/WORKSPACE
rules_nodejs_to_rules_js_migration/WORKSPACE
ts_project_transpiler/WORKSPACE
vue/WORKSPACE.bazel
write_source_files/WORKSPACE

chore: update to latest aspect rules

---

oci_python_image/BUILD.bazel
oci_python_image/WORKSPACE
oci_python_image/configure.bzl
oci_python_image/fetch.bzl
oci_python_image/hack/README.md
oci_python_image/hack/runfiles.bzl
oci_python_image/hello_world/BUILD.bazel
oci_python_image/hello_world/__main__.py
oci_python_image/hello_world/app.py

- New feature or functionality (change which adds functionality)
No tests added yet.

feat: example for python integration with rules_oci

---

oci_python_image/MODULE.bazel
oci_python_image/hello_world/BUILD.bazel
oci_python_image/hello_world/test.yaml

chore: add test for container image

---

oci_python_image/hello_world/test.yaml

chore(oci-python): assert correct entrypoint

---

git_push/MODULE.bazel
git_push/defs.bzl

- Refactor (a code change that neither fixes a bug or adds a new feature)

fix: remove usage of private expand_template api

---

oci_go_image/MODULE.bazel
oci_java_image/BUILD.bazel
oci_java_image/MODULE.bazel
oci_python_image/MODULE.bazel

ran bazel test in these three folders

chore(deps): update rules_oci to latest

---

react-cra/WORKSPACE

- Bug fix (change which fixes an issue)
- Fixes issue #241 
Bumps the version of aspect_rules_ts to the latest version (1.4.5)

Updates aspect_rules_ts in react-cra example

---

angular-ngc/WORKSPACE.bazel
angular-ngc/defs.bzl
angular-ngc/package.json
angular-ngc/packages/common/BUILD.bazel
angular-ngc/packages/lib-a/BUILD.bazel
angular-ngc/packages/lib-a/src/lib/lib-a.component.scss
angular-ngc/pnpm-lock.yaml
angular-ngc/tools/sass.bzl
angular-ngc/tools/sass_workaround.bzl

- New feature or functionality (change which adds functionality)

feat: show a sass import

---

ts_project_transpiler/BUILD

I tried to follow through on this idea at one point, but lambdas aren't legal in BUILD files.
---
None

chore: remove TODO that can't be TODONE

---

angular-ngc/packages/common/package.json
angular-ngc/packages/lib-a/package.json

The package.json has to tell TS to look inside the src folder
Fixes #239
I verified there aren't red squiggles anymore.

fix: tsconfig pathmapping

---

react-cra/BUILD.bazel
react-cra/MODULE.bazel
react-cra/package.json
react-cra/pnpm-lock.yaml
react-cra/src/BUILD.bazel

Verifying downstream for rules_ts 2.0

refactor(react-cra): use swc to transpile

---

vue/tsconfig.json

---
- New feature or functionality (change which adds functionality)
Follows https://docs.aspect.build/rules/aspect_rules_js/docs/faq/#making-the-editor-happy
**For changes visible to end-users**
n/a
- New test cases added

feat: Add IDE setup in Vue example

---

.github/workflows/ci.yaml
bufbuild/BUILD.bazel
bufbuild/WORKSPACE
bufbuild/app/BUILD.bazel
bufbuild/app/main.go
bufbuild/app/pb/BUILD.bazel
bufbuild/app/pb/buf.gen.yaml
bufbuild/app/pb/help.proto
bufbuild/buf.bzl
bufbuild/repositories.bzl
bufbuild/toolchain.bzl

- New feature or functionality (change which adds functionality)
- New test cases added

feat: add buf.build example

---

jest/src/BUILD.bazel
jest/tsconfig.json

Adding sourcemaps for better debugging to the jest example.

jest: include sourcemaps in example

---

oci_python_image/MODULE.bazel
oci_python_image/hello_world/BUILD.bazel
oci_python_image/hello_world/test.yaml

- Refactor (a code change that neither fixes a bug or adds a new feature)
Needs https://github.com/aspect-build/rules_py/pull/194 first

refactor: use rules_py instead

---

oci_python_image/hello_world/BUILD.bazel
oci_python_image/py_layer.bzl

This is more similar to the shape that our customers would actually want to vendor.

refactor: make our py_layers into a reusable macro

---

protobufjs/.bazelrc
protobufjs/WORKSPACE.bazel
protobufjs/defs.bzl
protobufjs/package.json
protobufjs/pnpm-lock.yaml

---
- Chore: Uses protobufjs@7
**For changes visible to end-users**
- Suggested release notes are provided below: Upgraded protobufjs from 6.0.0 to 7.0.0

feat: Uses protobufjs@^7

---

.bazelignore
.bazelversion
MODULE.bazel
MODULE.bazel.lock
pyproject.toml
speller/README.md
speller/announce/BUILD.bazel
speller/data_driven_tests/BUILD.bazel
speller/greeting/BUILD.bazel
speller/lookup/lookup-test.cc
speller/main/BUILD.bazel
third_party/README.md
third_party/nlohmann-json/BUILD.bazel
third_party/nlohmann-json/README.md

More coming, deeper in the file tree. Have mostly looked at the top level so far as a starting point.

Additional minor top-level comments

---

logger/README.md
logger/frontend/BUILD.bazel
logger/frontend/package.json
pnpm-lock.yaml

---
- Searched for relevant documentation and updated as needed: yes
- Breaking change (forces users to change their own code or config): no
- Suggested release notes appear below: no
ran `npm start` and observe live website changes after saving a change in index.html

chore: make frontend server auto-refresh

---

.aspect/cli/config.yaml
BUILD.bazel
MODULE.bazel
MODULE.bazel.lock
logger/client/src/build/aspect/JavaLoggingClientLibrary.java
pmd.xml
tools/lint/BUILD.bazel
tools/lint/linters.bzl

Demonstrates how Marvin will review this code which introduces a suspicious code pattern.

feat: add java linting

---

README.bazel.md
tools/_multitool_run_under_cwd.sh
tools/_run_under_cwd.sh
tools/buf
tools/buildozer
tools/docker-compose
tools/go
tools/ibazel
tools/multitool
tools/pnpm
tools/terraform
tools/tools.lock.json

pnpm is especially useful for frontend engineers

feat: add more utility tools

---

package.json
pnpm-lock.yaml
pnpm-workspace.yaml
tools/BUILD.bazel
tools/package.json

See https://github.com/aspect-build/rules_lint?tab=readme-ov-file#format for example - by converting asciinema to animated SVG we can embed these directly in a readme file!

chore: install svg-term for capturing demos

---

bazelrc/README.md

Fix broken link in bazelrc/README

---

.bazelversion
.gitattributes
MODULE.bazel.lock
WORKSPACE.bazel

chore: update bazel

---

.aspect/workflows/bazelrc
.aspect/workflows/config.yaml
logger/client/src/build/aspect/BUILD.bazel
logger/schema/BUILD.bazel
oci_go_image/BUILD.bazel
oci_python_image/hello_world/BUILD.bazel
tools/platforms/BUILD.bazel

It was disabled here
https://github.com/aspect-build/bazel-examples/commit/6749298dea7f016245bf1eb5568d1a64a96a1386#diff-c543330d148f738e9f3033a8afb70fec440c9328ae3d8f7b0019cc459b880c28L9

feat: enable RBE again

---

MODULE.bazel
angular/package.json
angular/projects/my-app/BUILD.bazel
angular/projects/my-app/src/app/app.html
angular/projects/my-app/src/app/app.ts
angular/projects/my-lib/src/lib/my-lib.ts
angular/tsconfig.json
pnpm-lock.yaml

Follows the typical javascript idioms, like an Nx workspace would do.

feat(angular): demonstrate monorepo dependency

---

MODULE.bazel

chore(deps): rules_angular is now published
