aspect-build/bazel-examples

angular-ngc/defs.bzl, angular-ngc/packages/lib-a/BUILD.bazel
I realized this isn't even used. I probably did it while trying to debug those npm link issues...
=> example(angular-ngc): remove unused ng_pkg(data)

bazelrc/.bazelrc
When adding `--incompatible_allow_tags_propagation`, it should be added for fetch and query too. Otherwise users of `query`-based tooling like `ibazel` or the `gopackagesdriver` of `rules_go` invalidate their analysis graphs whenever those tools run.
=> Add incompatible_allow_tags_propagation to fetch and query

ts_project_transpiler/BUILD, ts_project_transpiler/tsconfig.json
Today a few things in here will (correctly) break without the fixes to rules_swc along with the `ts_project(transpiler)` changes:
* today `ts_project` declares the js+map outs so it works with swc despite not passing `swc(source_maps = "true")`
* if swc was producing maps they are in a different directory then declared by `ts_project` (https://github.com/aspect-build/rules_swc/pull/107)
=> test: add ts transpiler predeclared output tests

next.js/bazel/next.bzl
We were seeing readonly filesystem errors on Linux when using a single file `out`. This outputs a directory and `out_dirs` produces the correct behavior.
=> Use `out_dirs` for `next` macro output

angular-ngc/WORKSPACE.bazel, angular/WORKSPACE.bazel, directory_path/WORKSPACE, jest/WORKSPACE, nestjs/WORKSPACE, next.js/WORKSPACE.bazel, pnpm-workspaces/WORKSPACE.bazel, protobufjs/WORKSPACE.bazel, react-cra/WORKSPACE, rules_nodejs_to_rules_js_migration/WORKSPACE, ts_project_transpiler/WORKSPACE, vue/WORKSPACE.bazel, write_source_files/WORKSPACE
Will bump bzlmod example in a follow-up after https://github.com/bazelbuild/bazel-central-registry/pull/376 lands
=> chore: update to rules_js 1.15.0

vue/vite.config.ts
It seems like `@yourname/yourlibrary` has its own copy of vue in its `node_modules` and as a result Vite is including both in the bundle. The fix here instructs Vite to de-duplicate the library. There may be other approaches to fixing this such as having the library reference a version of vue defined at the workspace level, but the solution in this PR is also fairly conventional.
resolves: https://github.com/aspect-build/bazel-examples/issues/66
=> fix: duplicate includes of Vue

angular-ngc/WORKSPACE.bazel, angular-ngc/applications/demo/BUILD.bazel, angular-ngc/applications/demo/app/app.component.html, angular-ngc/applications/demo/app/app.module.ts, angular-ngc/applications/demo/app/dragula.component.ts, angular-ngc/applications/demo/polyfills.ts, angular-ngc/applications/demo/styles.css, angular-ngc/package.json, angular-ngc/pnpm-lock.yaml, angular-ngc/tools/test-bootstrap.js, angular/BUILD.bazel, angular/WORKSPACE.bazel, angular/package.json, angular/pnpm-lock.yaml, angular/src/app/app.component.html, angular/src/app/app.module.ts, angular/src/app/dragula.component.ts, angular/src/polyfills.ts, angular/src/styles.css
Adds `ngcc` to the rules_js bin, adds a peer dep on `@angular/compiler-cli` and runs `ngcc` as a `custom_postinstall`.
=> example(angular-ngc): add custom_postinstall ngcc example

.gitignore, oci_go_image/BUILD.bazel
Before these changes, only pkg_tar was transitioned which led to an incorrect base image being chosen independently from the arch of the binary. 
Fixes # (issue)
How has this been tested?
If part of the test plan included manual testing, please provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
=> fix: transition oci_image instead of pkg_tar only

vue/package.json
`//:dist` is not a valid label since that output is a tree artifact which is not pre-declared.
**Type of change**
**Test plan**
Ran the build script
=> fix: fix build-only script in vue example

next.js/bazel/next.bzl
The `/apps/alpha` package does not contain `next_js_binary` for this example.
=> example(next.js): fix docs label for next_js_binary location

.github/workflows/ci.yaml, react-cra/src/BUILD.bazel
Works-around a ts_project worker issue that only manifests on macos.
---
- Bug fix (change which fixes an issue)
=> fix: disable ts_project workers //src:src_test_ts target in react-cra example to fix issue on macos

oci_python_image/hack/README.md, oci_python_image/hello_world/BUILD.bazel, oci_python_image/py_image_layer.bzl, oci_python_image/workaround_rules_pkg_153/BUILD.bazel, oci_python_image/workaround_rules_pkg_153/runfiles.bzl
The stuff we would keep after rules_pkg#153 is fixed is now split out to a starlark module in the root folder.
---
- Refactor (a code change that neither fixes a bug or adds a new feature)
=> refactor: clarify what's a workaround for rules_pkg

oci_go_image/BUILD.bazel, oci_go_image/MODULE.bazel
Updates the `oci_go_image` example to use the latest version of `rules_oci` and other dependencies. 
```
jparraga@U-1DJORH1PD9VGC:~/code/bazel-examples/oci_go_image$ bazel build ...
DEBUG: gazelle@0.27.0/MODULE.bazel:7:6: WARNING: The bazel_gazelle Bazel module is still highly experimental and subject to change at any time. Only use it to try out bzlmod for now.
DEBUG: rules_go@0.37.0/MODULE.bazel:8:6: WARNING: The rules_go Bazel module is still highly experimental and subject to change at any time. Only use it to try out bzlmod for now.
DEBUG: rules_go@0.33.0/MODULE.bazel:7:6: WARNING: The rules_go Bazel module is still highly experimental and subject to change at any time. Only use it to try out bzlmod for now.
INFO: Analyzed 7 targets (110 packages loaded, 11672 targets configured). …
```
=> Update oci_go_image example

vue/package.json, vue/pnpm-lock.yaml
CI has been red on main here for a while :(
It was passing for me locally, and I'm still not sure why I couldn't reproduce the failure.
But the error message gave a good hint about the missing dependency edge:
```
Error: Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.
at resolveCompiler (/home/runner/.cache/bazel/_bazel_runner/1a25d1b0ca5c1d8983b0a6c902cca550/execroot/__main__/bazel-out/k8-fastbuild/bin/node_modules/.aspect_rules_js/@vitejs+plugin-vue@3.2.0/node_modules/@vitejs/plugin-vue/dist/index.cjs:16:11)
```
=> chore(vue): fix red CI

oci_python_image/MODULE.bazel, oci_python_image/hello_world/BUILD.bazel
but actually used index.docker.io/library/python
Fix it to really use distroless like we claimed
=> fix(oci_python): we misnamed our repo distroless_python 

vue/libraries/simple/vite.config.ts
The Vite config for the library was including Vite in the bundle. This PR removes Vite from the library's bundle which results in a fix for the exported component. 
**Before**
```console
runtime-core.esm-bundler.js:40 [Vue warn]: Invalid VNode type: Symbol(Fragment) (symbol) 
at <InputText> 
at <App>
```
**After**
---
- Bug fix (change which fixes an issue)
`bazel run :vite`
=> fix: [Vue warn]: Invalid VNode type

pnpm-workspaces/apps/alpha/src/main.ts
---
- Bug fix (change which fixes an issue)
Failed with 
```console.log((0, _starwarsquotes.default)());
^
TypeError: (0 , _starwarsquotes.default) is not a function
```
**For changes visible to end-users**
- Suggested release notes are provided below:
rules_js pnpm examples now runs without fail
```cd pnpm-workspaces && bazel run //apps/alpha:main```
=> Fix import for star wars quotes in rules_js example

.aspect/cli/config.yaml, .bazelrc, .clang-tidy, .pre-commit-config.yaml, BUILD.bazel, MODULE.bazel, MODULE.bazel.lock, README.bazel.md, buf.yaml, eslint.config.mjs, logger/frontend/BUILD.bazel, logger/frontend/index.ts, logger/frontend/tsconfig.json, package.json, pnpm-lock.yaml, pnpm-workspace.yaml, speller/announce/announce.cc, speller/data_driven_tests/lookup-datatest.cc, speller/lookup/lookup-test.cc, speller/lookup/lookup.cc, speller/main/build-dictionary.cc, speller/main/spell.cc, tools/lint/BUILD.bazel, tools/lint/linters.bzl
Five linters are setup so far in the root module: clang-tidy, eslint, shellcheck, ruff, and buf. 
Ran 'bazel lint //...' to demonstrate they are working - see comments on this PR for demonstrations of each language.
=> feat: add linting

.aspect/cli/rules_cc.star, .github/workflows/ci.yaml, jest/README.md
Saves us some GitHub Actions resource limit exhaustion, especially since we'll recommend that users send PRs here to play with Marvin.
It avoids them getting spammed with a dozen irrelevant github statuses here as well. This was a problem when I gave a demo today: had to scroll down to find the Aspect Workflows status.
Note: this affects lands to `main` as well. That means a nested module may be red at HEAD, but subsequent test runs don't re-test it and go back to green again. In a real user repository this would probably not be desirable behavior.
---
Try changing some files in this PR and see what matrix jobs run
=> chore: don't kick off github actions jobs for unchanged nested Bazel modules

.aspect/cli/config.yaml, BUILD.bazel, MODULE.bazel, MODULE.bazel.lock, checkstyle.xml, tools/lint/BUILD.bazel, tools/lint/linters.bzl
---
```
bazel lint logger/client/...
Lint results for //logger/client/src/build/aspect:JavaLoggingClientLibrary:
{
"$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
"version": "2.1.0",
"runs": [
{
"tool": {
"driver": {
"downloadUri": "https://github.com/checkstyle/checkstyle/releases/",
"fullName": "Checkstyle",
"informationUri": "https://checkstyle.org/",
"language": "en",
"name": "Checkstyle",
"organization": "Checkstyle",
"rules": [
],
"semanticVersion": "10.17.0",
"version": "10.17.0"
}
},
"results": [
```
=> chore: setup checkstyle linter for Java

.gitignore, pnpm-workspaces/.aspect/bazelrc/bazel6.bazelrc, pnpm-workspaces/.aspect/bazelrc/convenience.bazelrc, pnpm-workspaces/.aspect/bazelrc/correctness.bazelrc, pnpm-workspaces/.aspect/bazelrc/javascript.bazelrc, pnpm-workspaces/.aspect/bazelrc/performance.bazelrc, pnpm-workspaces/.aspect/cli/config.yaml, pnpm-workspaces/.bazelrc, pnpm-workspaces/BUILD.bazel, pnpm-workspaces/MODULE.bazel, pnpm-workspaces/apps/alpha/BUILD.bazel, pnpm-workspaces/apps/beta/BUILD.bazel, pnpm-workspaces/defs.bzl, pnpm-workspaces/packages/first/BUILD.bazel, pnpm-workspaces/packages/one/BUILD.bazel, pnpm-workspaces/packages/shared/BUILD.bazel, pnpm-workspaces/packages/two/BUILD.bazel
Update rulesets, fully generate BUILDs, update to latest recommendations for rule naming, use of `js_library` for packages etc.
=> build: update pnpm-workspaces example

.bazeliskrc, pnpm-workspaces/BUILD.bazel, pnpm-workspaces/apps/alpha/BUILD.bazel, pnpm-workspaces/apps/alpha/src/main.ts, pnpm-workspaces/packages/one/BUILD.bazel, pnpm-workspaces/packages/one/src/lib.ts, pnpm-workspaces/packages/shared/BUILD.bazel, pnpm-workspaces/packages/shared/src/lib.ts
BUILD files can now be cleared out and fully re-generated with `configure` without any diff
=> chore: update gazelle generation in pnpm-workspaces examples

.bazeliskrc, WORKSPACE.bazel
It was removed in #390 but that broke 'bazel configure'. Also upgrade Aspect CLI to latest while I'm here, though it didn't fix anything
=> chore: restore WORKSPACE file

.github/workflows/sync_mirrors.yaml
Note, I put deploy public keys into each of the downstream repos, the private keys are stored in GHA secrets in this repo.
NB: this assumes that the push is a fast-forward, meaning we prevent commits to those two downstream repos directly. If it's not a fast-forward, this new GHA workflow will fail on the `git push` step.
@gregmagolan are you okay with making any GHA or CCI edits to this repo and then letting the automation push them? If not I'll have to do something fancier here to rewrite commits on top of the history of the target repo, essentially a rebase.
---
Will run the new workflow manually at first.
=> chore: mirror commits from bazel-examples to downstreams

.github/workflows/sync_mirrors.yaml
Fixes red X appearing on those repos, e.g. https://github.com/aspect-build/bazel-examples-gha/commit/3a12238ddd307c5843d847cb282b4c294962aa7c
Note, I tried using a matrix job to reduce duplication here, but it got very difficult to debug the SSH credentials not working. You can't just put both of them into the ssh-agent based on my testing. Not worth my time.
=> fix: don't try to run sync job from downstreams

oci_go_image/BUILD.bazel, oci_go_image/main.go, oci_go_image/main_test.go
locally running `bazel coverage` on this target
```
% cat /private/var/tmp/_bazel_alexeagle/2442372bc9d5c407aa13d3b43880afe0/execroot/_main/bazel-out/darwin_arm64-fastbuild/testlogs/oci_go_image/app_test/coverage.dat
SF:oci_go_image/main.go
FNF:0
FNH:0
DA:9,1
```
=> chore: add a go_test so we can measure some coverage

.bazeliskrc, angular-ngc/.aspect/cli/config.yaml, angular-ngc/.aspect/cli/postcss.star, angular-ngc/BUILD.bazel, angular-ngc/applications/demo/BUILD.bazel, angular-ngc/applications/grpc/BUILD.bazel, angular-ngc/packages/connect/src/proto/BUILD.bazel, angular-ngc/packages/lib-a/BUILD.bazel
Upgrade the aspect-cli to the latest pro version. Generate the angular-ngc `sass_binary` targets automatically.
---
- Searched for relevant documentation and updated as needed: yes
- Breaking change (forces users to change their own code or config): no
- Suggested release notes appear below: yes
Add example aspect orion plugin for BUILD generation.
=> feat: generate angular-ngc sass_binary targets with aspect configure plugin

oci_python_image/hello_world/integration_test.py
Fixes the incremental loader to find the largest chain in the layers and start loading from there.
=> fix: adjust incremental loader to find the largest chain

.bazelignore, REPO.bazel
pre-factor for Angular example
---
=> refactor: use Bazel 8 feature to ignore node_modules

rules_nodejs_to_rules_js_migration/bazel/rules_js_to_rules_nodejs_adapter.bzl
This will break as it doesn't do the full upgrade, it just creates the start so that I can pull a copy of the upgraded file into our internal repo
=> Update rules_js_to_rules_nodejs_adapter.bzl for rules_js 2.0

BUILD.bazel, py_mypy/cli/BUILD.bazel, py_mypy/data_models/BUILD.bazel, py_mypy/data_persistence/BUILD.bazel, py_mypy/inventory_management/BUILD.bazel, py_mypy/order_processing/BUILD.bazel, tools/mypy/BUILD.bazel, write_source_files/bar/BUILD.bazel, write_source_files/foo/BUILD.bazel
Some config to reduce the errors+diff when running `bazel configure`
---
- Manual testing; `bazel configure`
=> chore: configure+buildifier BUILD files

.aspect/bazelrc/performance.bazelrc, .pre-commit-config.yaml, MODULE.bazel, oci_python_image/hello_world/BUILD.bazel, pnpm-lock.yaml, tools/BUILD.bazel, tools/_run_under_cwd.sh, tools/ng, tools/package.json
- Update the rules_js version to pick up Bazel 8 rctx.watch fixes
- Bump node.js version as required by Angular CLI
- Switch to alias pattern for _run_under_cwd.sh like our 'aspect init' template now has
Prefactoring for stamping out a new Angular example
---
Ran `./tools/ng help` and `./tools/ng version`
=> chore: add Angular CLI to tools

.aspect/workflows/config.yaml, oci_go_image/BUILD.bazel
avoids having the auth problem of exposing credentials on a public repo
=> chore: push to an anonymous registry

.aspect/cli/rules_cc.star, .aspect/workflows/config.yaml, .circleci/config.yml, BUILD.bazel, gazelle_python.yaml, logger/backend/cmd/server/BUILD.bazel, logger/cli/BUILD.bazel, logger/schema/BUILD.bazel, oci_go_image/BUILD.bazel, oci_python_image/BUILD.bazel, oci_python_image/hello_world/BUILD.bazel, oci_python_image/hello_world/test.yaml, py_mypy/BUILD.bazel, requirements/BUILD.bazel, speller/announce/BUILD.bazel, speller/data_driven_tests/BUILD.bazel, speller/greeting/BUILD.bazel, speller/lookup/BUILD.bazel, speller/main/BUILD.bazel, write_source_files/bar/BUILD.bazel, write_source_files/foo/BUILD.bazel
Otherwise our training courses trip over errors when running `configure`. We want to keep it green and no-changes-prompted.
=> chore: turn on configure checking

.aspect/workflows/bazelrc
Green up angular tests which don't know how to find chrome on the AMI
=> fix: let Angular tests know where chrome is install on the AMI
